name: "Setup AWS CodeArtifact"
description: "Sets up the dotnet build environment to use AWS CodeArtifact"
inputs:
  aws-code-artifact-nuget-source:  # id of input
    description: 'Fully Qualified NuGet Feed Source'
    required: true
  nuget-feed-name:  # id of input
    description: 'Fully Qualified NuGet Feed Source'
    required: false
    default: 'NeoAgi'

runs:
  using: "composite"

  steps: 
  # Add the 3.1 SDK, needed to install the AWS Code Artifact Credential Provider
  - name: Setup .NET Core 3.1
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: 3.1.x
    env:
      DOTNET_NOLOGO: "true"
      
  - name: Setup .NET 6.0
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: '6.0.*'
      
  - name: Print Core Versions
    run: | 
      dotnet --version
      aws --version
      dotnet nuget --version
    shell: bash
      
  - name: Prepare NuGet Repository
    run: | 
      dotnet tool install -g AWS.CodeArtifact.NuGet.CredentialProvider
      dotnet codeartifact-creds install
      dotnet nuget remove source nuget.org
      dotnet nuget add source "${{ inputs.aws-code-artifact-nuget-source }}" -n "${{ inputs.nuget-feed-name }}"    
    shell: bash
  
  - name: List NuGet Configuration
    run: dotnet nuget list source
    shell: bash