name: "Setup AWS CodeArtifact"
description: "Sets up the dotnet build environment to use AWS CodeArtifact"
inputs:
  aws-code-artifact-nuget-source:  
    description: 'Fully Qualified NuGet Feed Source'
    required: true
  nuget-feed-name:  
    description: 'Short Name for NuGet Repository Source'
    required: true
  target-sdk-version: 
    description: 'Target SDK Version to Install'
    required: false
    default: '6.0.*'

runs:
  using: "composite"

  steps: 
  - name: Setup .NET 6.0
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: ${{ inputs.target-sdk-version }}
    env:
      DOTNET_NOLOGO: "true"
      
  - name: Print Core Versions
    run: | 
      dotnet --version
      dotnet nuget --version
    shell: bash
      
  - name: Prepare NuGet Repository
    run: | 
      dotnet tool install -g AWS.CodeArtifact.NuGet.CredentialProvider
      dotnet codeartifact-creds install
      dotnet nuget remove source nuget.org
      dotnet nuget add source "${{ inputs.aws-code-artifact-nuget-source }}" -n "${{ inputs.nuget-feed-name }}"    
    shell: bash
  
  - name: List NuGet Configuration
    run: dotnet nuget list source
    shell: bash
